<a href="https://colab.research.google.com/github/PriyankaRaj15/AI-ML-Month/blob/main/DL_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

In [ ]:
torch.__version__

'2.0.1+cu118'

In [ ]:
data=[[1,0,1,0],[1,0,1,1],[0,1,0,1]]
x=torch.tensor(data)

In [ ]:
x.size()

torch.Size([3, 4])

In [ ]:
x.device

device(type='cpu')

In [ ]:
tensor=torch.tensor([4,7,8])
tensor

tensor([4, 7, 8])

In [ ]:
tensor+5

tensor([ 9, 12, 13])

In [ ]:
tensor_2=torch.tensor([9,5,0])


In [ ]:
a=tensor+tensor_2
b=tensor*tensor_2

tensor([36, 35,  0])

In [ ]:
a

tensor([13, 12,  8])

In [ ]:
b

tensor([36, 35,  0])

In [ ]:
x=torch.tensor([[1,2,3],
                [7,8,9]])

In [ ]:
y=torch.tensor([[4,5,6],[2,7,5]])

In [ ]:
x*y

tensor([[ 4, 10, 18],
        [14, 56, 45]])

In [ ]:
%%time

torch.matmul(x,y.T)#can also write mm for matmul
c=torch.mm(x,y.T)

CPU times: user 314 µs, sys: 15 µs, total: 329 µs
Wall time: 2.46 ms


In [ ]:
c

tensor([[ 32,  31],
        [122, 115]])

In [ ]:
%%time
x@y.T
#%%time

CPU times: user 97 µs, sys: 8 µs, total: 105 µs
Wall time: 109 µs


tensor([[ 32,  31],
        [122, 115]])

In [ ]:
torch.linspace(1,100,20)

tensor([  1.0000,   6.2105,  11.4211,  16.6316,  21.8421,  27.0526,  32.2632,
         37.4737,  42.6842,  47.8947,  53.1053,  58.3158,  63.5263,  68.7368,
         73.9474,  79.1579,  84.3684,  89.5789,  94.7895, 100.0000])

In [ ]:
torch.randint(1,10,size=(3,4))

tensor([[3, 7, 3, 7],
        [6, 6, 6, 9],
        [4, 4, 4, 3]])

In [ ]:
x=torch.randint(1,100,size=(20,))

In [ ]:
x.max()

tensor(97)

In [ ]:

x.sum()

tensor(1026)

In [ ]:
x.type(torch.float32).mean()

tensor(51.3000)

In [ ]:
x.shape


torch.Size([20])

In [ ]:
x.reshape(5,4)

tensor([[32, 21, 37, 35],
        [51,  5, 64, 43],
        [97, 33, 93, 18],
        [96, 37, 67,  7],
        [88, 47, 58, 97]])