In [76]:
import pandas as pd
data=pd.read_csv('C:/Users/Dell/Downloads/stroke.csv')
data

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [ ]:
countplot,boxplot,scatterplot

In [53]:
x=data.iloc[:,1:11].values
x

array([[1, 67.0, 0, ..., 228.69, 36.6, 'formerly smoked'],
       [0, 61.0, 0, ..., 202.21, nan, 'never smoked'],
       [1, 80.0, 0, ..., 105.92, 32.5, 'never smoked'],
       ...,
       [0, 35.0, 0, ..., 82.99, 30.6, 'never smoked'],
       [1, 51.0, 0, ..., 166.29, 25.6, 'formerly smoked'],
       [0, 44.0, 0, ..., 85.28, 26.2, 'Unknown']], dtype=object)

In [14]:
y=data.iloc[:,11].values
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [81]:
import sklearn
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
%matplotlib inline

In [61]:
from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()
encod_gender=data['gender'].values
encod_gender=lc.fit_transform(encod_gender)
print(encod_gender)
encod_marr=data['ever_married'].values
encod_marr=lc.fit_transform(encod_marr)
print(encod_marr)
encod_work=data['work_type'].values
encod_work=lc.fit_transform(encod_work)
print(encod_work)
encod_resi=data['Residence_type'].values
encod_resi=lc.fit_transform(encod_resi)
print(encod_resi)
encod_smok=data['smoking_status'].values
encod_smok=lc.fit_transform(encod_smok)
print(encod_smok)
encod_bmi=data['bmi'].values
encod_bmi=lc.fit_transform(encod_bmi)
print(encod_bmi)
encod_age=data['age'].values
print(encod_age)
encod_hyp=data['hypertension'].values
print(encod_hyp)
encod_hear=data['heart_disease'].values
print(encod_hear)
encod_gluc=data['avg_glucose_level'].values
print(encod_gluc)

[1 0 1 ... 0 1 0]
[1 1 1 ... 1 1 1]
[2 3 2 ... 3 2 0]
[1 0 0 ... 0 0 1]
[1 2 2 ... 2 1 0]
[239 475 198 ... 179 129 135]
[67. 61. 80. ... 35. 51. 44.]
[0 0 0 ... 0 0 0]
[1 0 1 ... 0 0 0]
[228.69 202.21 105.92 ...  82.99 166.29  85.28]


In [93]:
x=np.vstack((encod_gender,encod_age,encod_hyp,encod_hear,encod_marr,encod_work,encod_resi,encod_gluc,encod_bmi,encod_smok))
x=x.transpose()
y=data.iloc[:,11].values
print(x)
print(y)

[[  1.    67.     0.   ... 228.69 239.     1.  ]
 [  0.    61.     0.   ... 202.21 475.     2.  ]
 [  1.    80.     0.   ... 105.92 198.     2.  ]
 ...
 [  0.    35.     0.   ...  82.99 179.     2.  ]
 [  1.    51.     0.   ... 166.29 129.     1.  ]
 [  0.    44.     0.   ...  85.28 135.     0.  ]]
[1 1 1 ... 0 0 0]


In [74]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [79]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(solver='lbfgs',max_iter=10000)
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print(y_pred)
print(y_test)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [83]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[964,   0],
       [ 58,   0]], dtype=int64)

In [85]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf=RandomForestClassifier(n_estimators=3,criterion='entropy')
classifier_rf.fit(x_train,y_train)
y_pred=classifier_rf.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[951,  13],
       [ 56,   2]], dtype=int64)

In [88]:
#accuracy=93%